In [1]:
import pandas as pd
test_df = pd.read_csv('csv/grid/test.csv')
test_df.head()

,video_id,vert_aperture,outer_vert_aperture,horiz_spread,inner_area,outer_area,compactness,lip_speed,rms_energy,digit_sequences,digit_sequences_filename,digit_segments
0,grid/s24/bbac9n,"[0.00420692558296937, 0.005589503978696907, 0....","[0.17340637006542853, 0.18713639483185815, 0.1...","[0.5289792014859723, 0.5231187311762354, 0.508...","[0.012222924505685228, 0.010027829640825481, 0...","[0.0388903031950574, 0.03905123770622916, 0.03...","[0.1112580689997699, 0.11238607485909023, 0.11...","[0.006021348293500415, 0.010293642491568035, 0...","[0.013150403276085854, 0.015377274714410305, 0...","[""bin"", ""blue"", ""at"", ""c"", ""nine"", ""now""]",NaN,"[[16, 21], [22, 28], [29, 31], [32, 37], [38, ..."
1,grid/s24/bbad1p,"[0.0011514728907117803, 0.001793812890899889, ...","[0.18029314638569696, 0.18040975870778153, 0.1...","[0.5154573532689349, 0.5009818128571045, 0.501...","[0.024524487768864837, 0.02293673032158479, 0....","[0.05386138522921654, 0.052878991703981484, 0....","[0.1580688779775401, 0.16358910563129855, 0.16...","[0.014489785053284158, 0.007083449962253374, 0...","[0.0017849091673269868, 0.0025079913903027773,...","[""bin"", ""blue"", ""at"", ""d"", ""one"", ""please""]",NaN,"[[15, 21], [22, 27], [28, 31], [33, 37], [38, ..."
2,grid/s24/bbad2a,"[0.0021880416412204877, 0.002351482992887519, ...","[0.18615646979135314, 0.1855272959345746, 0.18...","[0.503328196306317, 0.502086012212229, 0.49800...","[0.012491558147152644, 0.012661151494807822, 0...","[0.04039346341723712, 0.0408456257615758, 0.04...","[0.1250652495437557, 0.12689997981541387, 0.12...","[0.001252890417809882, 0.0026775389886784526, ...","[0.004055608529597521, 0.006074839737266302, 0...","[""bin"", ""blue"", ""at"", ""d"", ""two"", ""again""]",NaN,"[[16, 22], [23, 29], [30, 34], [35, 39], [40, ..."
3,grid/s24/bbadzs,"[0.0006855727353399541, 0.0013337742254965206,...","[0.14467886639197547, 0.15273294429289855, 0.1...","[0.5129242085608202, 0.5136755170328292, 0.513...","[0.017531284119687175, 0.016998316089865063, 0...","[0.04072817731408218, 0.04213372722809681, 0.0...","[0.12705404847267007, 0.12964164546818344, 0.1...","[0.0009922850356392974, 0.00041523573343555455...","[0.0027996732387691736, 0.004469257313758135, ...","[""bin"", ""blue"", ""at"", ""d"", ""zero"", ""soon""]",NaN,"[[25, 31], [32, 41], [42, 45], [49, 53], [54, ..."
4,grid/s24/bbaj3n,"[0.12821379328083116, 0.13146225038278064, 0.1...","[0.29828545939545176, 0.2981979053045567, 0.30...","[0.480513928822978, 0.48109665937004814, 0.481...","[0.01691756774288799, 0.01744407092478751, 0.0...","[0.04542002125363052, 0.04568846179204958, 0.0...","[0.13128602646098766, 0.13177014055350472, 0.1...","[0.003300310354147732, 0.001885750584924732, 0...","[0.008085313253104687, 0.009438417851924896, 0...","[""bin"", ""blue"", ""at"", ""j"", ""three"", ""now""]",NaN,"[[13, 19], [20, 26], [27, 29], [30, 36], [37, ..."

In [3]:
import json
df = pd.read_csv('csv/grid/test.csv')
len(json.loads(df.loc[2, "vert_aperture"]))

75

In [4]:
test_df['vert_aperture'][0]

'[0.00420692558296937, 0.005589503978696907, 0.007193979211756378, 0.05068606956598954, 0.08159355183915343, 0.09793482630738361, 0.10329024923037995, 0.10455344401016947, 0.10300964952930317, 0.10269942249873017, 0.10177823959683253, 0.10365249845130922, 0.07439452757946112, 0.02921856030995688, 0.004881458625619524, 0.004863338871800656, 0.005966608671848263, 0.07901102810559124, 0.13030578707513846, 0.13400045281251224, 0.12356923388289812, 0.015371754308680298, 0.003420775603093937, 0.0033609056854021174, 0.06072729594558476, 0.1138217328820903, 0.12090398091611795, 0.07614388117342798, 0.03856878670298035, 0.06495062024548783, 0.08192556574168129, 0.08464599000702769, 0.08658749708601994, 0.0867750095031007, 0.09153422263672112, 0.10165054238391051, 0.1244022755398516, 0.1284077483890415, 0.1254283601560048, 0.10771741460856384, 0.09564797070869695, 0.10240411634712564, 0.11359538648672196, 0.12207231993469851, 0.1267558793016585, 0.12829409790766752, 0.106540140520304, 0.10644060141227771, 0.11417241467878507, 0.10645216701486693, 0.11116661053399683, 0.12874651533868958, 0.13266302032515404, 0.12906212103173695, 0.12615049864312647, 0.09413858066290826, 0.03340266446925977, 0.0188742433017157, 0.02651904897474476, 0.03316071007382874, 0.039378294396683326, 0.03315477863444593, 0.01955926053392483, 0.008520241749936352, 0.007501118822821816, 0.006093360443303769, 0.0068840234288848725, 0.0075765635481874405, 0.006104946996987968, 0.0067434306058521765, 0.00662227753901205, 0.005513205769702651, 0.004904108723940326, 0.004545241900486972, 0.0047026324560431034]'

In [52]:
frame_df = pd.read_csv('csv/test_frames.csv')
frame_df.head()

,video_id,frame_idx,vert_aperture,outer_vert_aperture,horiz_spread,inner_area,outer_area,compactness,lip_speed,rms_energy
0,subset_01/subset_01/1100/1_1100_male_202503051...,0,0.031858,0.231533,0.505643,0.002099,0.032273,0.092437,0.000335,0.000000e+00
1,subset_01/subset_01/1100/1_1100_male_202503051...,1,0.031555,0.231541,0.505502,0.002074,0.032250,0.092416,0.001829,4.880944e-08
2,subset_01/subset_01/1100/1_1100_male_202503051...,2,0.028305,0.230462,0.504773,0.004095,0.033335,0.095747,0.005180,5.062728e-04
3,subset_01/subset_01/1100/1_1100_male_202503051...,3,0.024288,0.226518,0.512885,0.005300,0.035791,0.100542,0.006312,1.485352e-03
4,subset_01/subset_01/1100/1_1100_male_202503051...,4,0.023394,0.222937,0.516401,0.005148,0.035692,0.099665,0.008685,2.639090e-03

In [38]:
print(test_df['video_id'][0])
print(test_df['video_id'][1])

subset_01/subset_01/1100/1_1100_male_20250305175437_392!9456_Hinovaphone-Hera-BD00-Android11_train_1
subset_01/subset_01/1100/1_1100_male_20250305175440_40358267_Hinovaphone-Hera-BD00-Android11_train_2

In [44]:
test_df['digit_segments'][4]

'[[13, 16], [18, 22], [24, 29], [31, 35], [37, 41], [43, 46], [48, 51], [53, 67]]'

In [48]:
test_df['digit_sequences'][0]

'["3", "9", "2", "9", "4", "5", "6"]'

In [42]:
len(test_df['vert_aperture'][1])

1388

In [43]:
test_df['vert_aperture'][0]

'[0.03185812454443402, 0.031554723610500525, 0.028304983838668113, 0.02428795340357536, 0.02339368199991249, 0.008158840824624668, 0.00759004574910437, 0.007196970458911387, 0.0075312637119312915, 0.007017920506105166, 0.010016622111518731, 0.010975578110106788, 0.007186731213970961, 0.012775012648153929, 0.005338672281495794, 0.005794431191547781, 0.006366394372242317, 0.009134509273500319, 0.010184650014885758, 0.014807267821238188, 0.014900564007216534, 0.021196887853838373, 0.020782392505104226, 0.019066923644731736, 0.01679997048555541, 0.01150822157220412, 0.019576861202855362, 0.04159552244978199, 0.03897569253174771, 0.031890541794714136, 0.027582605080010255, 0.03591936724006177, 0.03853038406464102, 0.03129665209951017, 0.02298258054321594, 0.01795904252709332, 0.01397121022960762, 0.006754793378414267, 0.006410921379619856, 0.00837386665185696, 0.010435733562623875, 0.010880425385528521, 0.005849450507700941, 0.005159819502611472, 0.0064883670593414615, 0.00523529078046912, 0.005152666347812739, 0.00605124519605905, 0.006418517909932515, 0.006893762172923189, 0.005232777969299873, 0.0051126184518519285, 0.004482260487197705, 0.0037374792349288747, 0.00486994092439215, 0.017745184282731554, 0.024568256160661342, 0.021234258249447847, 0.02070524898304101, 0.008685850497010771, 0.007684978530588839, 0.0051695642797722225, 0.005419168740512823]'

In [29]:
df = pd.read_csv('csv/train.csv')
row = df.iloc[0]
vert_ap = row['vert_aperture']
len(vert_ap)

1525

In [1]:
import torch
torch.cuda.is_available()

True

In [1]:
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

In [ ]:
model_path = "data/face_landmarker.task"


BaseOptions = mp.tasks.BaseOptions
FaceLandmarker = mp.tasks.vision.FaceLandmarker
FaceLandmarkerOptions = mp.tasks.vision.FaceLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = FaceLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.IMAGE)

with FaceLandmarker.create_from_options(options) as landmarker:
  # The landmarker is initialized. Use it here.
  # ...
    pass

## VIsualization Utils

In [3]:
%matplotlib inline

In [ ]:
#@markdown We implemented some functions to visualize the face landmark detection results. <br/> Run the following cell to activate the functions.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from mediapipe.tasks.python.vision import drawing_utils
from mediapipe.tasks.python.vision import drawing_styles
import numpy as np
import matplotlib.pyplot as plt


def draw_landmarks_on_image(rgb_image, detection_result):
  face_landmarks_list = detection_result.face_landmarks
  annotated_image = np.copy(rgb_image)

  # Loop through the detected faces to visualize.
  for idx in range(len(face_landmarks_list)):
    face_landmarks = face_landmarks_list[idx]

    # Draw the face landmarks.


    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_TESSELATION,
    #     landmark_drawing_spec=None,
    #     connection_drawing_spec=drawing_styles.get_default_face_mesh_tesselation_style())
    drawing_utils.draw_landmarks(
        image=annotated_image,
        landmark_list=face_landmarks,
        connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_CONTOURS,
        landmark_drawing_spec=None,
        connection_drawing_spec=drawing_styles.get_default_face_mesh_contours_style())
   
    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_LEFT_IRIS,
    #       landmark_drawing_spec=None,
    #       connection_drawing_spec=drawing_styles.get_default_face_mesh_iris_connections_style())
    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_RIGHT_IRIS,
    #       landmark_drawing_spec=None,
    #       connection_drawing_spec=drawing_styles.get_default_face_mesh_iris_connections_style())

  return annotated_image

def plot_face_blendshapes_bar_graph(face_blendshapes):
  # Extract the face blendshapes category names and scores.
  face_blendshapes_names = [face_blendshapes_category.category_name for face_blendshapes_category in face_blendshapes]
  face_blendshapes_scores = [face_blendshapes_category.score for face_blendshapes_category in face_blendshapes]
  print("Face Blendshapes category names: ", face_blendshapes_names)
  print("Face Blendshapes category scores: ", face_blendshapes_scores)
  # The blendshapes are ordered in decreasing score value.
  face_blendshapes_ranks = range(len(face_blendshapes_names))

  fig, ax = plt.subplots(figsize=(12, 12))
  bar = ax.barh(face_blendshapes_ranks, face_blendshapes_scores, label=[str(x) for x in face_blendshapes_ranks])
  ax.set_yticks(face_blendshapes_ranks, face_blendshapes_names)
  ax.invert_yaxis()

  # Label each bar with values
  for score, patch in zip(face_blendshapes_scores, bar.patches):
    plt.text(patch.get_x() + patch.get_width(), patch.get_y(), f"{score:.4f}", va="top")

  ax.set_xlabel('Score')
  ax.set_title("Face Blendshapes")
  plt.tight_layout()
  plt.show()

In [ ]:
# STEP 2: Create an FaceLandmarker object.
import cv2
model_path = "face_landmarker.task"
base_options = python.BaseOptions(model_asset_path=model_path)
options = vision.FaceLandmarkerOptions(base_options=base_options,
                                       output_face_blendshapes=True,
                                       output_facial_transformation_matrixes=True,
                                       num_faces=1)
detector = vision.FaceLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("face1.png")

# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
plt.imshow(annotated_image)

In [ ]:
# STEP 3: Load the input image.
image = mp.Image.create_from_file("face2.png")

# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
plt.imshow(annotated_image)

In [2]:
from model import SequenceVerifier, DigitVerifier
model = SequenceVerifier()
model

SequenceVerifier(
  (lip_encoder): LipEncoder(
    (conv): Sequential(
      (0): Conv1d(5, 32, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(32, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
    )
    (gru): GRU(64, 128, batch_first=True, bidirectional=True)
    (fc): Linear(in_features=256, out_features=64, bias=True)
  )
  (digit_embedding): Embedding(11, 64)
  (digit_compare): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=64, out_features=1, bias=True)
  )
  (seq_agg): Sequential(
    (0): Linear(in_features=8, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [4]:
model = DigitVerifier()
model

DigitVerifier(
  (lip_encoder): LipEncoder(
    (conv): Sequential(
      (0): Conv1d(5, 32, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(32, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
    )
    (gru): GRU(64, 128, batch_first=True, bidirectional=True)
    (fc): Linear(in_features=256, out_features=64, bias=True)
  )
  (digit_embedding): Embedding(11, 64)
  (classifier): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=64, out_features=1, bias=True)
  )
)